### ISSUE TITLE
Kaart overhaul

### ISSUE THREAD

**Issue by EAT-CODE-KITE-REPEAT** [EAT-CODE-KITE-REPEAT/mastercrimez4#13]
###  Before deploying:
- [x] change all Lisbon in users.city to Porto
- [x] change cities.city Lisbon to Porto
### Verder
- [x] Release voor Android + iOS in BETA mode, alleen BETA TESTERS (level 2) kan hierbij, en kan deze hele modus aanzetten via Settings
- [x] Toon ook bezittingen op territorium view, bombarderen vanuit zelfde header-view-pager
- [x] Maak bombarderen voor territoriums + bezittingen vanuit MapView werkend. Deprecate de oude bezitting bombardering pagina.

# Web Release
- [x] Haal viewpager weg. omdat het niet werkt i.c.m. web. Kom ik laat achter zeg. Opties: snap-carousel voor iOS/Android, en gewoon een View (evt met pijltjes) op web.
- [x] Render polygons en overlays hetzelfde als op app zoveel mogelijk
- [x] Maak alles werkend op Android
- [x] Maak mogelijk om te kiezen tussen game versies in instellingen als je level >2 bent
- [x] Test of normale versie nog goed werkt
- [x] upload ios transporter
- [x] upload release android en release
- [x] fix vage bugs huidge versie op app

# 5 dec
- [x] Als propertyOwner none is, toon dan geen 'bomb' maar 'takeOver'
- [x] als jij propertyOwner bent, toon dan 'beheer' onderaan bij die bezitting
- [x] Toon netjes op de kaart als je aan 't vliegen of jail zit, toon niet meer zo lelijk met vol screen
- [x] Split up income
- [x] Maak hoeren/junkies/wiet-cap afhankelijk van je eigen + je gangs territoriums
- [x] Split up shop
- [x] Begin met Stock Exchange
- [x] maak endpoint voor repair(areaId)
- [x] maak bomb(areaId) mogelijk
- [x] verlies territoriums bij gekilled
- [x] maak acties bij territorium: takeEmptyArea, repair, bomb, 
- [x] zorg dat je zo nodig captcha's kan invullen via popup met `await getCaptcha`
- [x] beveilig alles met captcha
- [x] Maak gym, hospital, markt ook geld verdienend: gym krijgt gewoon 10miljoen per dag, hospital krijgt healkosten, markt krijgt 50% van transactiekosten
- [x] Territorium Achievement Gang, GangBank achievement, Gang bullets achievement

# Todo 4 december

ERGERNISSEN
- [ ] Hij is langzaam als je op een gebouw klikt, en alles knippert dan
- [ ] Als je teruggaat vanuit een menu blijft het scherm ff hangen
- [x] Geen titel van wat je aanklikt. Wat is het?
- [x] Tekst bovenin niet goed leesbaar
- [x] Bij bombarderen ga je naar een nieuw scherm, is niet nodig
- [x] Header niet goed leesbaar
- [x] Stats/Chat/More heeft een navigation header, zou er niet moeten zijn
- [x] Ik wil members online zien, niet stats, als eerste menu
- [x] Alle bezittingen mist bij stats
- [x] my properties kan naar status
- [x] als je eigenaar van een bezitting bent, moet dit duidelijk aangegeven zijn bovenin bij de bezitting
- [x] lijntje onder 'everyone'chat
- [x] pijltje in header terwijl dit de homepage is
- [x] Stats bij more of bij chat is niet gewenst
- [x] Je kan niks met territoriums
- [x] Werkt niet op Android
- [x] Werkt niet op Web, hoe ga ik daar deze functionaliteit integreren?
- [x] oc/streetrace/robberies worden nog niet getoond. get alle ocs, streetraces en robberies, en plaats ze op de kaart. vernieuw om de 1 minuut en met een vernieuw knop
- [x] make + knop go to createOC, createStreetrace, createRobbery
- [x] add param to OC, Streetrace, Robbery with id: the ID you clicked, to show just that one

- [x] maak object size afhankelijk van city delta, net als bij movende objects (markers)

### Objects
- [x] kies positiegetal deterministisch aan de hand van een string van `moment().format("DD-MM-YY HH")` en `index` en `type`
- [x] kies aan de hand van positiegetal een deterministische area waar de object in moet: we hebben `polygon`
- [x] maak functie op de frontend die aan de hand van polygon en positiegetal een pseudorandom punt kiest in de polygon
- [x] Werken, wiet

### Gebouwen goed
- [x] Plaats een stockExchange als gebouw en voeg het toe aan het model als bezitting
- [x] Plaats een RLD of stripclub als gebouw
- [x] Plaats een coffeeshop ipv een farm als gebouw

### Overig
- [x] Zorg dat in steden met minder territoriums alsnog 14 objecten kunnen worden geplaatst
- [x] Zorg dat in grotere steden de iconen wat groter zijn, en in kleinere steden wat kleiner
- [x] add '+'knop voor nieuwe OC, nieuwe streetrace, nieuwe winkelroof, etc.

# Map Actions
- [x] Maak als je klikt op de gebouwen actieknoppen onderaan, swipable horizontal viewpager als 't er meer zijn. clash-of-clans style. Doel: de gebruiker zoveel mogelijk tijd laten besteden op de kaart. de kaart niet hoeven te verlaten voor de meeste acties.
- [x] toon bij klikken op een gebouw altijd de stats (eigenaar, schade, profit, etc)
- [x] render een grijze cirkel achter het gebouw als je hem geselecteerd hebt zodat het duidelijk is
- [x] maak van autostelen, misdaden, hoeren, junkies, wiet, gewoon actieknoppen. bij hoeren/junkies/wiet ook inkomen ophalen. bij auto/misdaden beginner/gevorderd/expert die allemaal een action sheet openen
- [x] bij stats moet een Properties-tab zijn waar je ALLES kan zien van ALLE bezittingen (alleen beschikbaar voor betaald account)
- [x] casino: poker, lotto, bombardeer
- [x] hospital: heal jezelf, heal een ander [invoerveld], bombardeer
- [x] bulletfactory: koop kogels, gang BF, bombardeer
- [x] airport: vlieg naar --> opent actionsheet, vliegtuigwinkel, bombardeer
- [x] jail: meer info (navigate), bombardeer
- [x] coffeeshop: bombardeer, inkomen ophalen
- [x] rld: bombardeer, inkomen ophalen
- [x] leger des heils: bombardeer, inkomen ophalen
- [x] house: status, bunker, schoentje zetten
- [x] bank: bank, switserse bank, donate, bombardeer
- [x] headquarter: create gang, headquarter, gangshop, missions
- [x] weaponshop: buy weapons, buy protection, bombardeer
- [x] gym: train, bombardeer
- [x] garage: garage, racecars, bombardeer
- [x] markt: markt, bombardeer

# Todo 3 december

Grote Gebouwen in 3d iconen
- [x] Kogelfabriek / gang kogelfabriek
- [x] Hospital
- [x] Sportschool: 
- [x] Gevangenis
- [x] Garage + Racecars
- [x] Bank
- [x] Markt
- [x] Casino
- [x] Wapenwinkel
- [x] Beschermingwinkel
- [x] Vliegtuigenwinkel
- [x] Je huis: zelf plaatsen waar! Dit is status, schoen zetten, en bunker
- [x] Garagewinkel bij garage in
- [x] Vliegveld
- [x] Wietplantage: zelf bouwen, ergens op de kaart
- [x] Bombing
- [x] Gang huis (hoofdkwartier): Gangshop, gangmissies
- [x] Beurs

Kleinere units
- [x] Misdaden: pistooltjes op de kaart her en der, alleen als je kan
- [x] Junkies: poppetjes verspreid op de kaart, alleen als je kan zoeken
- [x] Prostitutes: Poppetjes verspreid op de kaart, alleen als je kan
- [x] Auto stelen: op random locaties autootjes plaatsen

- [x] toon badges op sommige gebouwen
- [x] add coordinates voor elke stad in de db
- [x] pak coordinates van gebouwen automatisch door een grid te maken van 16 gebouwen rondom en de crimes etc. in het midden. hetzelfde voor elke stad
- [x] maak gebouwen mooi in photoshop
- [x] voeg de rest van de gebouwen toe, make sure dat ze niet worden afgesneden 
- [x] Verdeel stad in grid van een aantal pentagons en toon die bij territorium OF DOE WIJKEN. ZELF TEKENEN VIA REACT NATIVE.
- [x] bouw deze om tot state component en bouw een admin die automatisch Area.create aanroept met de nieuwe polygon https://github.com/react-native-maps/react-native-maps/blob/master/example/examples/PolygonCreator.js
- [x] DIT!! https://github.com/blackmad/neighborhoods
- [x] AirBnB heeft ook een goede dataset die wellicht NOG beter is, van allemaal geojson van wijken in steden
- [x] converteer de amsterdam multipolygon[] naar een polygon[] die vervolgens in een msyql table komt genaamd areas. deze kan je direct renderen zonder maps en is dus sneller als 't goed is
- [x] bereken van elke polygon een centrum, plaats daar een bezitting. plaats eronder een gang afbeelding
- [x] get deze data voor elke stad die ik nu heb, zorg dat reizen weer werkt
- [x] kijk hoe het eruit ziet als ik alles in 1 view prop. misschien best te doen.
- [x] minimize de data door voor elke wijk slechts 100 punten over te laten. 
- [x] maak een animatiee met vliegen die animeert naar je nieuwe stad binnen x seconden

# Todo 4 december
- [x] Header aanwezig als niet op mappage
- [x] Zorg dat MapArea database gevuld wordt zonder error 
- [x] Voeg gangId + userId toe aan MapArea, 
- [x] maak `/areas?city=x` endpoint die alle terri's in een stad teruggeeft inclusief user + gang
- [x] Maak post /takeEmptyArea 
- [x] get /areas op FE
- [x] Zoek vanuit de cityAreas op de frontend de bijbehorende /areas MapArea op basis van de MapArea.code
- [x] Maak het mogelijk om een takeEmptyArea(MapArea.id)
- [x] Toon `<User/>` + `<Gang/>` in `<ViewPager/>`
- [x] Area -> MapArea (rename)
- [x] Maak MapObject { latitude, longitude, size, icon, emoji, image }
- [x] Maak functie voor crew die objecten verplaatsen kan: post /moveBuilding
- [x] Maak dat je dmv slepen die endpoint aanroept, en alleen crew kan slepen
- [x] Maak een migratie die standaard de objecten op de centers van de territoriums zet voor elke stad
- [x] Pas het verder aan zodat het allemaal goed staat in elke stad
- [x] KLEUREN VOOR GANGS

# leuke ideeen: 

### Voor later
- [x] hoeren, junkies, wiet een cap op zetten van in bezit, afhankelijk van hoeveel territoriums je hebt. X per territorium kun je dan in bezit hebben.
- **NEE** een territorium kan een of meerdere bezittingen hebben. die bezittingen moeten ook eigendom zijn van dezelfde gang/persoon, wil je effectief wat kunnen met het territorium/de bezitting.
- **NEE** je kan misdaden, auto stelen, en winkelroof alleen in andermans territorium doen.
- **NOG NIET** je kan een huis kopen op een willekeurige plek in je eigen territorium. dit word dan weergegeven op de kaart
- **NEE** een territorium is altijd gezamenlijk eigendom van een gang.
- **NEE** elke speler kan 1 territorium verdedigen met z'n leven. die territorium kan je pas inpikken als je deze speler vermoord.
- **NEE** een bezitting kan je alleen eigenaar van zijn als je gang dat territorium heeft.
- **NEE** garages en wietplantages zijn dingen die je gang op z'n territorium kan bouwen. des te meer territoriums, des te meer plek voor je auto's en des te meer wietplantages kun je bouwen wat resulteert in meer wiet cap
