### ISSUE TITLE
Todo December

### ISSUE THREAD

**Issue by EAT-CODE-KITE-REPEAT** [EAT-CODE-KITE-REPEAT/mastercrimez4#17]
# Todo 
- [ ] Gebouwen blijven staan bij territorium view en crimes view
- [ ] Na uitbraak refreshed de lijst met gevangenen niet
- [ ] Trillen modal height 
- [ ] Er moet na kill power van gang verloren gaan en nadat achievements omlaag zijn ook
- [ ] Status pagina kan meer info op: woning wapens bescherming vliegtuig garage etc
- [ ] Je komt altijd even in Amsterdam uit als de game laadt
- [ ] add an "i" behind every building title, and also in some screens. There should be a short explanation for the screen there.
- [ ] add a "?" to the topleft of every screenmodal to open the bottomsheet with info about that screen.
- [ ] add {view}ViewInfo to translations and make the guy pop up upon first time clicking a view.
- [ ] in `<Modal>` add an array of texts for certain screens that are shown upon first open.
- [ ] Maak endpoint die de city top 3 uitspuugt (gangs) voor bezittingen en territoriums bij elkaar. Toon dit op stadspagina:
- [ ] maak het mogelijk een huis te bouwen op een territorium. dit territorium is dan: 1) moeilijker schade aan te brengen, 2) als je in die stad bent heb je thuis voordeel bij killen
- [ ] back button op web werkt niet meer
- [ ] Wanneer iemand gang leaved komt er geen melding meer van en kan niet meer terug joinen
- [ ] verwijder terri gangachievement
- [ ] fix level gang achievements level 0 is level 10
- [ ] zoeken bij leden werkt niet
- [ ] onderbaas kan baas verwijderen
- [ ] geef wonderwomen en elpatron een deel van hun verliezen terug, omdat ik ze vertrouw
- [ ] SkelettonView bij stats, leden, gangs, bezittingen
- [ ] push notificaties android schijnt niet te werken
- [ ] teksten bij mislukt misdaden
- [ ] gangkracht naar %'en en dit toevoegen aan kill bulletsNeeded
- [ ] logboeken toevoegen

# Email
- [ ] stap over naar mailerlite o.i.d. omdat sendgrid veel emails geblocked worden.
- [ ] Create proper email DNS records for receiving email
- [ ] Do everything to improve email receivability
- [ ] Send out emails too with supermessages from admin
- [ ] Send out email for gangs + prijzen + markt + layout release

# Admin UserWatch uitbreiding
- [ ] Controlleer of movements wel goed werkt, want sommige users hebben veel te veel. Word ook op de kaart movements bijgehouden?
- [ ] Zet keys/indexes op movements zodat het sneller werkt
- [ ] Transacties meten? Denk erover na. Dit kan een goede methodiek zijn om subs te vinden
- [ ] In een grafiek kunnen zien per timeframe hoeveel movements er plaatsvinden en hoeveel actions
- [ ] Bijhouden bij elke authenticated call per account of ze nogsteeds online zijn op het zelfde ip+device of dat ze geswitched zijn. dan per IP een overzicht maken op de x as de tijd en op de y-as de accounts die er speelden. Dit voor een week bijhouden. Ook de totale speeltijd per account/ip kunnen zien.
- [ ] Kunnen zien of actions een patroon volgen
- [ ] Kijken of actions een patroon volgen. Kijk naar de gemiddelde tijd tussen actions per action type, en de deviatie daarvan. Als de deviatie 0 is is het een bot met een simpele actioncall elke x seconden, waar x constant is. 
- [ ] NeedCaptcha variabel maken per speler. Als actions een patroon volgen, deze needCaptcha voor een week op 1 zetten. Hier een bericht voor sturen

## Retention
- [ ] Startersbonus voor spelers die een tijdje niet gespeeld hebben: Na een week niet online, elke week een bericht met 'He, je hebt al x weken niet gespeeld. Als je nu weer online komt krijg je een cadeautje van missie baas jaap!
- [ ] push notificatie/bericht als je je inkomen moet ophalen (>24u)

## Map minder belangrijk
- [ ] kijk of het mogelijk is om misdaden icons op coordinaten om de buildings heen te renderen, zodat ik alsnog de gameview en crimesview in 1 kan plaatsen
- [ ] je kan niet terug swipen als je een pagina hebt. zou heel vet zijn als het toch een stack wordt op de 1 of andere manier. en dan als je naar rechts swiped dan veeg je hem weg. als je naar links swiped ga je terug (of ook weg als terug niet meer kan)
- [ ] soms laadt hij alle gebouwen opnieuw, en dit duurt een paar seconden. hoe kan dit zolang duren?
- [ ] Gebouwen zijn scheef afhankelijk van locatie/latitude neem bij berekenen longitudeDelta de bolling van de aarde in acht, anders worden afbeeldingen te hoog/laag
- [ ] sneltoetsen maken voor map: k = kf, a = airport, etc. deze de-activeren als je in een input veld zit uiteraard, verder altijd actief. wow dit is vet
- [ ] gray out gebouwen waar je nog niks mee kan. Als je er dan op klikt, een opmerking krijgen dat je eerst x y z moet halen
- [ ] met ENTER een commandbar openen waar je alles in kan typen: spelersnamen, channels, territoriums, gebouwen, gangnamen, pagina's, en zelfs codes
- [ ] onHover alt text maken met de sneltoets

# SOUND
- [ ] geluiden en trillen als je op knoppen drukt in de app. dit aan en uit kunnen zetten. dit geeft het een echte feel
- [ ] achtergrond muziek: 1 theme song per stad, uiteraard uit kunnen zetten
- [ ] kijken of ik een music streamer kan maken die op RN en RN web werkt. Dan meer songs toevoegen

# Algemeen
- [x] test of Android werkt op Standalone app
- [ ] release ios, ook met nieuwe screenshots, engelse tekst
- [ ] implement [this](https://futurestud.io/tutorials/pm2-restart-processes-after-system-reboot)

# stats refactor
- [ ] add your position to the stats
- [x] use new usercomponent
- [ ] add most properties stat
- [ ] add best gangs stat
- [x] add icons and <Content> per stat
- [ ] translate titles

# Marketing

## SEO / ASO
- [ ] Improve visibility on Google
- [ ] Find a way to have good meta data for invite-a-friend links so it says what you get when you click there. 

## TikTok Challenge
- [ ] Let users submit short videos to win prizes. Showcase these after they're accepted. The TikTok video with the most likes that promotes MasterCrimeZ.com gets €100,  every month.

## FB Ads
- [ ] Create lookalike audience of paying players, try ads for like €10 per day for a while

- [x] toon als je helemaal uitzoomt de andere mogelijke steden waar je heen kan vliegen. vliegveld->vlieg zoemt voor je uit zodat je gewoon op de nieuwe stad kan klikken. als je op de stad klikt een alert met 'wil je naar x vliegen? Met je y kost het z euro en duurt a seconden: Ok/Annuleren'.
- [x] Voor territoriums elke week een nieuwe stad releasen. Voor de rest de kaart gewoon in de game knallen

## Done

- [x] gooi terri's dicht voor non-beta
- [x] Als je reist wil je een confirmatie doen voordat je daadwerkelijk reist, en je wil terug kunnen als je de worldview hebt
- [x]  een speler kan maar 1x per uur in de gevangenis worden gezet?
- [x] timer bij bombarderen action button
- [x] maak bescherming countdown op map
- [x] icoontjes misdaden staan soms te dicht op elkaar, heel irritant
- [x] sport school geel als je kan trainen
- [x] jail rood als er iemand in zit
- [x] klok gaat helemaal gek
- [x] isPolice killen geen spul stelen (kogels/bank)
- [x] iPhone 11 home screen toont 1 menurij achter de swiper
- [x] Als je op inkomens ophalen drukt en het uur is niet voorbij start de tijd dan weer opnieuw waardoor je veel inkomsten misloopt
- [x] nieuwe leden gelijk de locale goedzetten in de eerste /me query die eruit gaat zodat je eerste bericht goed is.
- [x] Rethink accomplices. Helemaal verwijderen? Hoe dan meerder auto’s stelen etc.?
- [x] ZB Rente van kogels naar 1%
- [x] properties in een andere stad mag je niet kunnen beheren. ook de knop weghalen bij status
- [x] ProfileScreen hooks error
- [x] Timers kunnen onder 0
- [x] Timers on finish werk niet
- [x] ShowMap false mode op mobiel niet aan kunnen zetten
- [x] Turn on/off newVersion kan weg
- [x] Hoeren refreshed steeds het plaatje 
- [x] Status bij je huis / bij gang refreshed niet
- [x] Max 1 OC/winkelroof/straatrace bij crimes is genoeg 
- [x] Crimes moeten uit elkaar liggen
- [x] Bij poker en Lotto wil ik cash/bank/Swiss zien
- [x] Modal moet boven titel uitkomen
- [x] Crash bij stock exchange 
- [x] Rerender gang profiel
- [x] Hoeren/junkies/wiet vanuit crimes pagina meteen doen (met captcha)
- [x] maak een overlay die je bij layout kan aanzetten die bij elke view over de hele kaart heenvalt behalve bij de territories view. hierdoor lijkt het net op de oude layout. kan alleen als menu aan staat, dus als je dat aan zet, zet menuShown op true. Alleen op web
- [x] gooi alles weg wat weg kan. grote schoonmaak nodig!
- [x] als je het spel voor het eerst opent een stad kunnen kiezen via vliegen. dan mooi naar de stad toe animeren. langzaam.
- [x] create my own fork of [this](https://github.com/gorhom/react-native-bottom-sheet/pull/14) + the most current version
- [x] add gangster2.png to the bottomsheet, with a text and ok button. make a component out of this. {text,onConfirm,onDismiss}
- [x] Make a me-state that says on which step you are in the demo
- [x] define the steps: welcome, choose name, choose city, do a crime, steal a car, search for junkies, go to the gym, buy a weapon, buy an airplane, bomb a territorium, etc. 
- [x] make texts for all demomissions
- [x] make the bottom sheet go behind the bottomtabs, actionbar, and title, and make sure the gangster is high enough above that.

# Me query niet doen in background
- [x] Als de app naar de achtergrond gaat stoppen met de me-query
- [x] Als de app naar de voorgrond komt weer beginnen met de me-query

## Done
# Make a RTE for MCZ 
- [x] gebruik die ene en maak net zoiets als slate want das cool
- [x] [this](https://github.com/DaniAkash/react-native-draftjs/pull/31) should be merged, then I will use it
- [x] [also interesting](https://github.com/asp3/react-native-rich-editor) (gebruikt nog components)
- [x] [this is what i need](https://github.com/imnapo/react-native-cn-richtext-editor)
- [x] [last option](https://github.com/reggie3/react-native-webview-quilljs)
- [x] Render HTML everywhere using something like [this](https://github.com/jsdf/react-native-htmlview)
- [x] Use RTE and save HTML on all kinds of places, like profile, gang profile, forum, chat, supermessage
- [x] Extrahere profile textEditor into component
- [x] use it on gang profile, forum, supermessage

- [x] centralize releasedates 
- [x] Header valt soms helemaal weg, maak dat weer normaal
- [x] timers of jail/flying in normal layout (web/app)
- [x] alertAlert werkt vaak niet
- [x] estateAgent menu
- [x] jezelf uitkopen werkt niet meer

### MAP
- [x] house and headquarter not lightblue
- [x] gangMembers uitspugen op /me zodat ik dat kan gebruiken voor specialColor
- [x] Voor territoriums elke week een nieuwe stad releasen. dit doen aan de hand van cityId*week vanaf releaseDate
- [x] sexshop, salvationarmy, coffeeshop geel maken indien onopgehaalde winst op map en op menu
- [x] release de nieuwe app in BETA, en als de feedback positief is over het algemeen, maak dan de hele app helemaal schoon: home weg, menus weg, navigation weg, etc. heel veel kan weg.
- [x] bij crimes: + knop is niet even hoog als menu knop
- [x] zet alle map-bestanden niet meer in /screens/map, maar in /layout
- [x] bij aanclicken van een channel, zet view op chat
- [x] bij geen owner andere specialColor: lichtblauw?
- [x] als je 'm overneemt update de owner niet bij territorium
- [x] titel blijft staan als je van building naar crime gaat
- [x] berichtenbalk refreshed niet. simpel weg routename als prop zetten en zorgen dat de balk opnieuw word binnegehaald bij deze prop change
- [x] bij chat view gaan gebouwen nog weg (app)
- [x] statsHeader klikken op je naam gaat naar je profiel, klikken op je gang gaat naar je gang.
- [x] createGang action key not found
- [x] index bug gebouwen
- [x] crimes navigate moet resetTo worden
- [x] bij stats wil ik wel een header
- [x] voeg header dingen toe zoals 'er is een nieuwe update' en 'dit speelt beter op de app' vanuit Header en Home
- [x] Dead, Jail, Vliegen goed afvangen
- [x] Show bunker time op overlay
- [x] Als params veranderen moet channel opnieuw laden
- [x] channelsubs query moet elke 5 sec gedaan worden in logic ipv in channels screen
- [x] in menu ook setRead afvuren bij channels
- [x] Streetrace menu toevoegen
- [x] Zet kies beroep en haal bescherming weg bij 'home' actions 
- [x] haal status weg
- [x] Header heeft een minheight, ook als ie helemaal weg moet zijn is ie er nog
- [x] onLongPress bij gebouwen een ActionSheet openen met alle gebouwen menu's
- [x] onLongPress bij misdaden een ActionSheet openen met alle misdaden menu's
- [x] bij sommige gebouwen wil je je stats zien. toon de stats dan op de pagina zelf (zoals winkel is cash/bank wel handig)
- [x] soms heb je toch een KAV nodig. bijv. bij chatten. fix dit overal waar nodig
- [x] haal overal city info weg, en plaats het properties menu in old layout
- [x] zet kogels en price van kf in properties info
- [x] maak ongeselecteerde areas minder opacity, geselecteerde meer opacity (web + app)
- [x] toon non-released dingen niet op de kaart en niet in het nieuwe menu. 
- [x] toon non-released dingen niet in ActionsBar
- [x] exporteer InactiveScreens naar 1 locatie
- [x] haal footer overal weg
- [x] Je kan een lege bezitting /bomb'en
- [x] alle nieuwe bezittingen doorvoeren op alle plekken in de code, code ook meer centraliseren qua type bezittingen
- [x] fix bombArea

## Map
- [x] fix garage
- [x] als je op een profiel op een property klikt moet je er heen kunnen navigeren mits je in dezelfde stad zit
- [x] overige zooi van Layout in de map knallen
- [x] zorg dat links werken met navigation op web (de belangrijkste is /#/Case/13241324 (of zonder #)
- [x] badges op gebouwen kunnen plaatsen
- [x] op web kan je een gebouw met een cirkel er overheen niet aanklikken omdat die er (altijd) over heen gerenderd wordt. zorg er simpelweg voor dat de circel clickable is
- [x] maak een Util functie van wat er allemaal gebeurd als je op territorium/gebouw klikt, zodat dit ook te gebruiken is in menu
- [x] soms animeert ie zomaar naar city als je op een pagina klikt meestal. Bvb zwitserse bank. waarom? WSL omdat cities reloaded wordt?
- [x] hij denkt dat ie (op web) nog gezoomd is als je uit zoomt en je gaat opnieuw naar een gebouw. zorg dat zoom geupdate wordt als je uitzoomt

### TabBar
- [x] badge bij TabBar items: chat, en meer.

### Header
- [x] breng de berichtenbalk terug op web, als je op een groot scherm zit
- [x] bij more en chat views geen statsheader tonen
- [x] bij crimes mag de bottom position lager van de modal. Modal automatisch top position aanpassen aan de hand van getLayout van header
- [x] modal kunnen sluiten met ESC
- [x] bij building home een deel van je status weergeven, misschien alles
- [x] bij building gang headquarter een gang status weergeven, de gang achievements bvb

### ActionBar
- [x] actionbar items moeten active kunnen zijn als bvb routeName hetzelfde is
- [x] jail heeft geen badge meer
- [x] ik wil badges bij inkomen ophalen 1u+, als gym kan, als je bezitting schade heeft

### Menus
- [x] Bezitting icoon kleur: rood=schade, geel=jouw profit, blauw=jouw, groen=gang
- [x] Terri icoon kleur: rood=schade, geel=jouw profit, blauw=jouw, groen=gang
- [x] Badges op menu's kunnen plaatsen
- [x] Badges bij unread chats
- [x] Badge bij jail
- [x] Voeg 'Alle chats' menu toe onderaan bij chats
- [x] probeer pointerEvents box-none op de height 100% menu view zodat als je alles inklapt je ook gewoon de map kan bewegen als je op het menu beweegt met je vinger/muis

### Other
- [x] kaart op nachtweergave zetten s nachts
- [x] zet eslint aan
- [x] menu's aan/uit kunnen zetten op web
- [x] menu's over map heen met opacity
- [x] trek menu's gelijk met side-menu's kaart: gebouwen, misdaden, territoriums links, en stats, chat, meer rechts. 
- [x] maak van channels en areas global dingen in screenProps
- [x] toon bij territoriums alle namen van alle wijken in het menu
- [x] toon bij chats je 10 meest recente channels in het menu
- [x] als je klikt op menu ook de juiste map->view zetten
- [x] als je klikt op gebouwen menu,niet navigeren maar gebouw selecteren en panTo/animateTo gebouw
- [x] Als je klikt op territorium menu, panTo/animateTo territorium
- [x] alle overige menu's bij more zetten
- [x] als je op kruisje drukt vanuit crimes ga je terug naar game view dat moet niet. in crimes blijven
- [x] Op elke bezittingpagina een boven of onderin een kleine kaart maken waar de bezitting op getoont wordt (web) 
- [x] kijken of ik op web alles in popups over de kaart heen kan tonen i.p.v. in nieuwe schermen zodat je je zoom en focus iet kwijt raakt (of de zoom/positie moeten worde opgeslagen in de store o.i.d. voor web)
- [x] denk erover na om settings, chat, en stats allemaal icoontjes te maken zoals game/territoriums/crimes, en hier komt dan een popup van over de kaart heen
- [x] iconclicks en actionbar navigations moeten resetTo worden
- [x] je moet de kaart niet kunnen draaien, dan worden de gebouwen lelijk
- [x] gebouwen/territoria hoeven niet perse weg te gaan bij stats/chat/more. anders is het zo leeg
