### ISSUE TITLE
Todo August

### ISSUE THREAD

**Issue by EAT-CODE-KITE-REPEAT** [EAT-CODE-KITE-REPEAT/mastercrimez4#6]
- [x] reset game
- [x] remove robot detection (for now) - keep it, but just save robo-number, don't do anything with it
- [x] make app work well on mobile with app-like navigation
- [x] add icons for all menus
- [x] make header
- [x] put menu items on home in a carousel so it looks like 

# More
- [x] Add settings menu to verify phonenumber
- [x] Add verifycomponent to layout so it always pops up when not verified
- [x] block actions when not SMS validated
- [x] Add updates available hook to game
- [x] Make chat nice
- [x] Add lightbrown as primary color to header and menu items bg
- [x] remove footer on app
- [x] don't expose city and bullets etc. for non-me people

# Deploy
- [x] put server online
- [x] deploy web
- [x] build:ios 
- [x] build:android

# Updates
- [x] Upgrade naar nieuwste expo variant
- [x] build:android
- [x] Add push notifications to settings
- [x] Send push notification when receiving message if available
- [x] put app in iOS appstore
- [x] put app in Android appstore
- [x] fix kill script (make it save against spam-bug)
- [x] check rob, shop, bank, income for spam-bug

# Cleanup, layout
- [x] For all items, make layout more beautiful
- [x] Add option to pay through mollie or so (on web)

# iOS store
- [x] maak testflight aan
- [x] test verification code 
- [x] verander not-verified box, add 'login to another account' button
- [x] provide apple with verified test-user
- [x] change screenshots (add stealcar and crime screenshot)
- [x] resubmit appstore connect
- [x] put content rating android up again
- [x] rebuild iOS app with sdk38. 
- [x] submit them to stores and do what they ask
- [x] app in ios store

# KF and other objects
- [x] screen
- [x] buy bullets api
- [x] model City with all cities inthere and bullets and bulletFactoryOwner
- [x] cron job every hour that adds bullets to all cities
- [x] ManageBulletFactoryScreen
- [x] show all cities in BulletFactoryScreen 
- [x] make it possible to takeObject on BulletFactoryScreen
- [x] Gevangenis, Casino, Vliegveld, RLD, Landlord (wiet), Leger des heils (junkies), wapenwinkel, makelaar, garage eigenaar
- [x] api manageObject: giveAway, changePrice, switchStatus, getProfit
- [x] on kill, set owner to null
- [x] set profit correctly
- [x] gevangenis mensen in de bak kunnen zetten

# Verify phone
- [x] users waar je niet op kan inloggen omdat ze geen email hebben geverifieerd, kunnen nu wel een telefoonnummer verifieren. Als je daarna die acc kwijtraakt, kun je niet meer met je telefoonnummer verder, en kan je dus niet spelen. Hier moet wat op gevonden worden. Wellicht ook je account kunnen recoveren met je telefoonnummer.
- [x] stuur mij een email als sms verzenden niet werkt

# Zwitserse bank + Garage winkel
- [x] kopieer bank frontend + backend naar SwissBank
- [x] negatieve rente over alles in CRON
- [x] geef dat ook mooi aan op de frontend
- [x] max aantal auto's in garage, kan geen auto stelen als je meer hebt dan dat in je garage

# Various
- [x] fix junkies frontend in app
- [x] betaalde accounts geel
- [x] >10k creditsTotal rood
- [x] admin (level 10) blauw
- [x] Maak erhan admin
- [x] superberichten feature voor 500 credits
- [x] voorkom spammen nieuw bericht
- [x] Maak settings / info screens mooi met icoontjes
- [x] Add themes (choose primary/secondary color sets) and customize background
- [x] add header titles for all menus
- [x] Rente 20:00 + push notificatie
- [x] ander icoon creditshop
- [x] header padding 3e regel
- [x] bescherming weghalen
- [x] showroom weg
- [x] bellen + creditshop
- [x] fix rank bug voor hoge ranks
- [x] credishop/mollie page fixen
- [x] stel creditshop in zodat het eerlijk is
- [x] number format alle grote getallen (vooral cash/bank)
- [x] Fix bug dat je niet kan killen
- [x] Mogelijkheid om al je contant geld in 1x te storten, en al je bankgeld in 1x op te nemen
- [x] sommige schermen zoals homescreen altijd beschikbaar, ongeacht bak, reizen, etc.
- [x] push notificatie bij kill, beroof
- [x] Add push notifications for when you can steal cars, misdaad, oc, etc. 
- [x] maak naam veranderen frontend opnieuw
- [x] maak alle settings pagina's mooi
- [x] add forum push notificaties
- [x] maak handlangers mooi, zodat het duidelijk is dat je die link kan delen, add Share.share functionality op app
- [x] polls
- [x] profilefoto bovenaan
- [x] dead people tax

# Menus samenvouwen
- [x] Bank,zw.bank, inkomen en doneren allemaal in 1 menu. Sla op welke tab in store
- [ ] VIP dingen samenvouwen in 1 ding: credits kopenn, creditshop en super bericht
- [ ] Admin dingen samenvouwen in 1 ding
- [ ] Aanvallen + beroven + backfire in 1 ding?
- [ ] status, statistieken, mijn bezittingen in 1 ding samenvatten

Voordeel: Je hebt maar anderhalve pagina nodig voor alle menu's, later misschien terug te brengen naar 1 pagina.

# Marketing
- [x] Referal link met Share knoppen op elke pagina: Facebook Share, Whatsapp Share, Snapchat Share, Telegram Share 
- [x] Social media knoppen op elke pagina, gewoon voor de likes: facebook, instagram, spotify, snapchat, youtube

# Ideetjes door inspiratie
- [x] Homepage met nieuws, acties, wachttijden, promoted members, tips voor beginners
- [x] Noem gamepoints respect
- [x] Krijg langzamerhand meer opties in het spel, begin simpel
- [x] Rank 2 decimalen is te veel, doe 1 decimaal of in het begin 0 decimalen
- [x] OC kan pas als je handlangers hebt
- [x] Bij statistieken kunnen zien hoeveelste jij zelf staat, ook bij me teruggeven en op status tonen
- [x] Elke rang omhoog moet je een bericht van krijgen
- [x] Wiet plantage veranderen naar Drugs maken?
- [x] Minder geld in het spel meer beter
- [x] Autostelen opsplitsen naar beginner/gevorderd/expert met tabjes. Sla op welke tab in store
- [x] ziekenhuis jezelf kunnen helen
- [x] Garage en racecars in 1 screen
- [x] Header aanklikbaar en met sharedelements een mooie animatie maken die hem dan uitvergroot zodat je meer kan zien, dan kan status weg.
- [x] uitleg bij schuilkelder e.d.
- [x] toon handlangers op profiel, niet als gang maar gewoon een getalletje
- [x] poker

# PRIO NU (15 Augustus)

# Casino

# Street race
- [x] Streetrace model, streetraceParticipant model
- [x] streetraceNew api
- [x] get streetraces api
- [x] streetrace screen waar alles samenkomt
- [x] streetraceJoin api
- [x] streetraceLeave api
- [x] streetraceStart api
- [x] put streetraces and cities in store so you can easily refresh it from any screen
- [x] don't expose all info of streetraceparticipants in streetrace query ,only necesary info
- [x] make sure you can't join a street race twice
- [x] if streetrace is full, show start button instead of leave button if you participated

# 16 augustus
- [x] test app on android, improve many aspects
- [x] re-release app on android
- [x] nieuw bericht notificatie klik --> automatisch naar bericht gaan
- [x] add links to download app at information 
- [x] add warning to mobile people that play in the browser: please download the app! (wegklikbaar)
- [x] maak na 3e keer openen app een review popup
- [x] add review us <3 at info

# misc.

- [x] Let op KAV overal
- [x] app in android store: google play console wait for email that it's approved
- [x] Bombarderen
- [x] Make messages more whatsapp like: channel system (copy from communify)
- [x] make sure you can't bashscript anything like stealcar, crime, gym, etc.
- [x] cronjob only once 
- [x] add [pagination](https://github.com/archriss/react-native-snap-carousel/blob/master/doc/PAGINATION.md)
- [x] user nudgen om push notificaties aan te zetten op veel plekken
- [x] Backfire klopt niet, je schiet niet met het aantal kogels teurgdat je. Hebt ingesteld
- [x] Handlangers klopt niet / is niet duidelijk
- [x] fix dat je niet dingen kan doen als je aan het reizen bent, dood bent, of in de gevangenis zit.
- [x] push notificaties aan zetten op homescreen (app)

**Comment by EAT-CODE-KITE-REPEAT** [comment]
TerrorMan

- Auto categorieën beter verdelen, nu kun je bij gevorderd vaak autos stelen die meer opbrengen in kogels/cash als bij expert. (hier mag je het aantal kogels ook best wel op verhogen.
- Er moet meer geld in het spel om een betere economie te creeëren, nu is alles in verhouding te duur.
- zorg dat je niet alleen bij misdaden moord-rang omhoog gaat maar bij alle activiteiten.
- maak misdaden doen uitgebreider, doe er plaatjes bij of maak er een kleine simulatie van dat als je een winkelroof doet dit op verschillende manieren kunt doen waarbij bij het een een lager risico is als bij een uitgebreidere of gedurfdere aanpak het risico dan ook hoger ligt.
- casino uitbreiden met blackjack en andere soorten kaartspellen en maak de kansen hoger (dit in samenhang met meer geld in het spel zodat met een casino meer geld te maken valt, evenals met andere bezittingen) 
- Meer buitenlandse steden of zelfs landen bijvoegen, waardoor vermoorden moeilijker word, nu is het nog rustig omtrent moorden maar zodra mensen genoeg kogelvoorraad hebben zal dit ongetwijfeld regelmatig plaats gaan vinden.
- fixed pricelist voor Kogelfabrieken, 1000 per kogel slaat totaal nergens op, maak er 100 van en zet dit vast zodat de spelers niet de macht hebben om iemand anders een poot uit te kunnen draaien. (hier hoor ik nu al een hoop geklaag over), zorg er tevens ook voor dat er per account ook maar 1 bezitting toegestaan is, anders krijg je zoals nu ook het geval is dat 1 iemand 5 kogelfabrieken in bezit heeft, dit is niet eerlijk ten opzichte van anderen.
- het zou gaaf zijn als je streetraces ook uitgebreider kan maken, dit is vrij simpel te realiseren door bepaalde onderdelen aan motorblok- ophanging- chassis- en toevoegingen zou maken.
- missies van jaap terughalen waar vooral beginners goed geld mee kunnen verdienen en snel kunnen ranken.

**Comment by EAT-CODE-KITE-REPEAT** [comment]
Puntjes van Erhan:

 - zou fijn zijn als je kan zien hoelang je in schuil zit
- er zijn heel veel subs
- je moet 1.5m wachten als je iemand zoekt, per stad. Dus ook al heb je hem niet kunnen aanvallen, best irritant. 
- aantal kogels per kill is echt absurd.. moest 730k gebruiken om een dangerous don te killen, u don is c.a 1.3m kogels dan.. ik stel voor dat we d don 420k kogels doen, u don 600k ofzo. 
- info pagina met alle tijden etc is ook erg handig
- verificatie loopt niet zo soepel; mensen krijgen duplicatie accs met dezelfde stats
- gele account en rode accounts moeten beter kunnen uitbreken en betere kans hebben op slagen met alles, meer rente ontvangen, minder betalen zwitserse bank, meer voordelen
