### ISSUE TITLE
Todo November

### ISSUE THREAD

**Issue by EAT-CODE-KITE-REPEAT** [EAT-CODE-KITE-REPEAT/mastercrimez4#9]
## gang
- [x] gang bullets als achievement
- [x] gang geld als achievement

# Other
- [x] kunnen zien of je in schuilkelder zit
- [x] bak/online/berichten query om de 5 seconden uitvoeren omdat dat veranderd
- [x] add dead:true prop to /members and make it possible to show dead members only
- [x] verzeker dat rangKnow bij doodgaan op nieuwe getal wordt gezet (of simpel weg 1)
- [x] rente moet om 20:00 komen, nederlandse tijdzone, niet om 22:00
- [x] clean up database and download a backup
- [x] add indexes in proper places database

# App release
- [x] Create screenshots with AppMockup
- [x] build aab and ipa
- [x] upload them to android
- [x] Add English screenshots/description on AppStoreConnect and GooglePlayConsole.
- [x] redo universal links on iOS, read well, make sure I can upload to Appstore Connect
- [x] upload to ios
- [x] Improve keywords in Appstore
- [x] make sure the URL mastercrimez.com gets opened with the app automatically, on Android and IOS, and the link gets forwarded to the right screens with right params

# Unimportant

## Open with app button
- [x] Instead of forcing a user to open the app, ask them politely by having a small panel on the bottom or top of the screen that says 'Open MasterCrimeZ App'. This should go to the download page if not present, or otherwise open the app with deeplink (if possible). Otherwise just have two options on this banner: 'Download the app' or 'Open the app'.
- [ ] Once opening the app with a deep link there should be the loginToken + name present in the deeplink. It should open a modal that asks you. "You are now logged in as X but on the website you were logged in as Y. [keep playing as X] [start playing as Y]". If account X is unverified, don't ask this question at all, just login as Y immediately.

# ------------------------------------
# -------------- DONE -------------------

# Markt
- [x] remove offer FE
- [x] test remove offer + go over code

# Killen
- [x] maken dat je -5 tot +5 rangen kan aanvallen 
- [x] Gang bank stelen bij killen
- [x] Log message naar gang ipv naar handlangers
- [x] removeAllOffers
- [x] junkies,hoeren,wiet, etc. door de heflt, controlleer dit.
- [ ] Gangs kunnen uitmoorden

# Prijzen
- [x] Initiate prize round vanaf 1 december 17:00: logo maken, mooiste profiel, meeste gamepoints, beste gang

# Change password refactor
- [x] seems not to work well

# New session onboarding + Retention

## Gradual Menus / release planner
- [x] Depending on play time, rank, strength, etc. show just a few menu's in the beginning. Once you play more, add menu's to it and show 'NEW' label at the menu.
- [x] update so level 2 is beta tester, level 3 is hulpadmin, level 5 is gamemod, level 10 is admin. frontend + backend
- [x] make Reject beta tester. He can see all features
- [x] make new features (front + backend) visible/accessible from a certain date for normal users
- [x] make it possible to schedule supermessages that also go out to email (but for sure to push notifications)
- [x] add isShareable prop to news messages so there is a whatsappp button below on the message so you can easily share news with friends

## Playability
- [x] nieuwe users 24uur bescherming
- [x] nieuwe users een welkomsbericht sturen

# Gangs: 1 december
- [x] Endpoints maken 16/16
- [x] GangCreateScreen
- [x] GangScreen
- [x] GangsScreen
- [x] GangShopScreen
- [x] GangSettingsScreen
- [x] Gang Transactions
- [x] GangAchievementsScreen
- [x] ganglevel moet weg als je een gang verlaat/joint
- [x] GangShop UI verbeteringen
- [x] 0.1 is mogelijk bij het opnemen of storten.
- [x] Wanneer je iets hebt overgemaakt krijg je alleen "overgemaakt" te zien, misschien wat mooier om te zien wat je overgemaakt hebt

# Markt: 15 december
- [x] create Market model
- [x] create endpoints: marketCreateOffer, marketTransaction, marketRemoveOffer, getMarket
- [x] create MarketScreen
- [x] UI markt screen
- [x] add transactions
- [x] testen

# Overig
- [x] fix image upload MyProfile iOS/Android, Improve UI
- [x] bank 'gepint'/'gestort' is niet vertaald

# BUGS
- [x] jezelf uitkopen werkt niet meer
- [x] soms log je even in op een ander account gek genoeg op mobiel
- [x] op anonymous safari tab is je nieuwe account undefined
- [x] make sure there arent any numbers as logintoken possible, prevent creation of those through api
- [x] if /me-query fails, generate new logintoken and try again on frontend
- [x] als je in bak zit blijven er requests vuren. elke keer als je in de bak komt, word er een nieuwe interval aangemaakt, dus het gaat steeds sneller, tot je ge-rate-limit word... https://upmostly.com/tutorials/setinterval-in-react-components-using-hooks
- [x] clear intervals everywhere neatly
- [x] make sure app fits on all iPhones and android phones.

# popup view
- [x] make are you sure view so I can use that view again (wrapper of alert.alert). 
- [x] implement this everywhere it's needed: gang settings for now

# New chat 
- [x] reload channels every 5 seconds and when you post a new message
- [x] reload chats every 5 seconds
- [x] doe wat aan weggelapte tekst in channels screen en chat screen
- [x] add it to menu, remove the old one
- [x] create function sendChatPushMail
- [x] add mail to sendChatPushMail
- [x] if push notifications are not received, also send out an email (if this option, which is on by default, is turned on in settings, and if the user has an email set, of course)
- [x] use nice html in sendChatPushMail mail
- [x] only send mail if user is not online
- [x] make system message look different
- [x] verzenden met enter
- [x] fix weird scroll behavior web (in channel)
- [x] use sendChatPushMail instead of sendMessageAndPush everywhere
- [x] fix upload image web, test iOs/android
- [x] word wrap op channels en in chat
- [x] test notificaties
- [x] remove old messages system completely
- [x] crash bij sommige RAAAR channels
- [x] make it possible to delete a message. just a prop isDeleted on channelsub, and this has to be set to false whenever a new message comes in this chat. 
- [x] langere berichten kunnen typen en niet verzenden met enter. maak het een textarea
- [x] Delete all feature maken bovenin
- [ ] probleem: als je je chats verwijderd kan je niet meer met je gang praten, totdat iemand anders dat zegt. oplossing: zoekfunctie inbouwen die ook verwijderde chats toont? of gangchannel onverwijderbaar maken? op zich is dit probleem niet heel groot, dus laat maar ff

# profile
- [x] show properties on profile
- [x] show gang on profile
- [x] remove accomplices

# Web with iframes 
- [x] add icons to menu
- [x] just like facebook, reserve more height for menus
- [x] make menu's on web in en uitklapbaar
- [x] make them scrollable within the height of the window, just like MKA/fb
- [x] make drawer menu look nice on every layout
- [x] stats next to logo

# layout
- [x] make <Content> Component that renders a slightly lighter background than the theme's background, with nice borderradius and padding/margin
- [x] use this everywhere, especially on places where it look rather ugly now, like gangsettings
- [x] make every content have a title and icon like MKA, and make them in/uitklapbaar. use localStorage to remember this setting among refreshes.
- [ ] give tabs icons, and make them look nicer. Make them scrollable if too many tabs don't fit the screen
- [ ] add some sort of 3d effect to button, use pressable and make the effect change when clicking it. it should be clearer that it's a button

# User render
- [x] make a function that renders an user with profile link, image, color, extra icons (beta tester, admin), country, online, mouseover, gang, gang image (image with 4 corners: 1: extra icon, 2: country, 3: online, 4: gang image - if available)
- [x] apply it everywhere. really. everywhere.
- [x] create a lazy profile that sends all user data that we already have to the profile to show it nicely, with a nice backbutton

# Translation
## Getting ready
- [x] Push device-language from frontend to user
- [x] Create language file on backend and put all Dutch in there
- [x] Create language file on frontend too and put all Dutch in there
- [x] make sure shop and creditshop work with translations
- [x] Make sure frontend sends locale to backend, also on web
- [x] All messages/push messages that are sent to users, should be translated to THEIR languages instead of the language of the user that sends them.
- [x] Change cities to European ones
- [x] Get mastercrimez.com
- [x] publish web on Vercel on mastercrimez.com
- [x] Add expo app.json thing to open mastercrimez.com with app automatically
- [x] Handle URL navigation properly if app is opened from website
- [x] redirect mastercrimez.nl to .com
- [x] Fix mollie webhook to use .com

## Add English
- [x] Add english according to TranslationGuide
- [x] Autostelen teksten vertalen

# Refresh me
- [x] all places where your token can change it should do a refresh of the app/website too, so that the setInterval changes to apply the new token.
- [x] add setInterval again. Test it well with loggin in again.

# Grids
- [x] https://github.com/GeekyAnts/react-native-easy-grid/ use this for tables
- [x] use it in gang settings
- [x] use it in gang profile

# no internet warning
- [x] make a warning when there is no connection with backend
- [x] make a warning like on mka when there is no or bad internet connection

# Layout
- [x] remove admin menu for normal users
- [x] use redux for remembering which menus are open
- [x] gang picture on gang header, your picture on your header
- [x] iconen overal goed
- [x] navigaten van stats goed
- [x] messages een batch in het rood maken
- [x] drawermenu ook goed maken
- [x] home voor web en app goed maken
- [x] use [this](https://gist.github.com/necolas/1c494e44e23eb7f8c5864a2fac66299a)-->hooks version  to add onHover bgColor changes
- [x] home onHover voor appknoppen

## Login modal
- [x] When opening the site on web on /Home or /Case or /Code or /StealCar on an unverified account, open modal
- [x] When opening the app for the first time, open modal
- [x] When clicking 'logout' in settings, open modal
- [x] In that modal, you can choose between: 'type in name --> just play' (new account) or 'login with email' or 'login with phone'. make sure that during this process, it doesn't loose the URL that the new user initially went to, so you can still make things sharable.
- [ ] add minWidth + minHeight

## reloadMe interval improvement
Now with the new loginmodal, the problem is we want to open the modal when a page loads for the first time, but we don't want to open it when it refreshes. and this is not possible. Therefore, we need to not have to refresh it when logging in. hence, we need the refreshMe interval to reset when a login happens. Maybe we can put the interval in a context to be able to reset it when needed.
- [x] Create reloadMeIntervalContext that provides context clearInterval and setInterval(token) to anywhere
- [x] Everywhere when logging in, clear interval and set new interval(token)

## Tell a friend / misdaden, auto stelen
- [x] Codes model { title, validUntil, action, carId (for cars), what, amount }
- [x] post enterCode endpoint to fulfil an action
- [x] bij zeer succesvolle misdaden (2% kans) een link aanmaken waar een koffer vandaan te halen is voor je vrienden en voor jou
- [x] Render invite link op misdaden indien aanwezig in post response
- [x] Code screens /Case /Code /StealCar die allemaal dezelfde component bevatten om een code te openen. Dit launched na druk op de knop een enterCode endpoint en laat zien wat de speler gewonnen heeft.
- [ ] bij auto stelen is er een kans (10% ofzo van success) dat je een auto bijna steelt, maar nog even hulp nodig hebt van een vriend. 
- [ ] maak ook code mogelijkheid bij auto stelen, hoeren, junkies, wiet.

## markdown everywhere 
- [ ] markdown editor web/app
- [x] markdown on profiles
- [x] markdown on gang profiles
- [x] markdown in forum
- [x] (simple) markdown in messages

**Comment by EAT-CODE-KITE-REPEAT** [comment]
- 0.1 is mogelijk bij het opnemen of storten. (Doet niet veel maar is wel een onnodige request)
- Casino is timeout gevoelig naar mij mening, na een time-out heb ik hogere payouts. 
	idee: Een pop-up (modal) met daarin een bericht dat iemand een time-out heeft. 
- Wanneer je iets hebt overgemaakt krijg je alleen "overgemaakt" te zien, misschien wat mooier om te zien wat je overgemaakt hebt
en hoeveel
- nummers automatisch converteren naar currency zodat punten en comma's worden weergeven en zo het bedrag beter te lezen is.
